### ISSUE TITLE
Handlebars error since vaultwarden update

### ISSUE THREAD

**Issue by Tchad90** [YoanSimco/vaultwarden-lang-fr#1]
Since the last update of vaultwarden (v1.32.1) when i invite user to an organisation i got an issue (cf below). When i disable email translation folder into my docker-compose. I got no more issue and invite are sent correctly.

![2024-10-08_16h14_39](https://github.com/user-attachments/assets/39287c51-2373-4acf-a9e0-94b943761f29)

**Comment by YoanSimco** [comment]
> Since the last update of vaultwarden (v1.32.1) when i invite user to an organisation i got an issue (cf below). When i disable email translation folder into my docker-compose. I got no more issue and invite are sent correctly.
> 
> ![2024-10-08_16h14_39](https://private-user-images.githubusercontent.com/85280463/374595692-39287c51-2373-4acf-a9e0-94b943761f29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDY3NTUsIm5iZiI6MTcyODQwNjQ1NSwicGF0aCI6Ii84NTI4MDQ2My8zNzQ1OTU2OTItMzkyODdjNTEtMjM3My00YWNmLWE5ZTAtOTRiOTQzNzYxZjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE2NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmY2IzOTc1MDNmNDgyZmFmYzRjNThiYzUwNWQzMzk3ZjVlZjZhZDRkYTlhYTM3NWUzYjdkY2M1NDFkYzgyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bG8_ehHw4eATWY90x_MzHwGWlpcNKhKkNHdziL1qIZc)

Thanks for the report!

Will fix this as soon as possible!

**Comment by YoanSimco** [comment]
Should be OK now!

**Comment by Tchad90** [comment]
> Should be OK now!

I confirmed. Thanks !
